# Isolated files

Easiest case. The typo can be fixed directly in the file on github.  This is super easy becasue you can do everything right on github.

Steps:

  1. Find the right file to make the change
  2. Make the edit directly 
  3. Submit the pull request

Appropriate when the content you are fixing is in a single file, and that file is not used to generate any other files in the repository.  It's easier to talk about exceptions, you can't use this method for:

* R help documentation generated using roxygen2 
* README.md when it is being generated by README.Rmd
* website files (i.e. HTML) that are generated from RMarkdown


## Make a change to README.md in the fixingrdocs package

Go through all steps right on github.

## What happens once you submit a PR

You wait...

## What is github handling that you need to do yourself for more complicated changes?

Forking  
Editing   
Comitting  
Issuing PR  

When you work off github:

Forking   
**Cloning**  
**Editing**  
**Comitting**    
**Pushing**   
Issuing PR

**Bold** now happens in RStudio


